# Generated by Django 5.1.6 on 2025-02-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_user',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='username',
        ),
    ]
