# Generated by Django 5.1.6 on 2025-02-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_doctor_appointment_doctor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='doctor_username',
        ),
        migrations.RenameField(
            model_name='genericuser',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='patient_username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
